services:
  app:
    build:
      args:
        user: brendan
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: urlshortener
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - urlshortener

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - urlshortener

  nginx:
    image: nginx:alpine
    container_name: nginx_urlshortener
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - urlshortener

networks:
  urlshortener:
    driver: bridge

volumes:
  redis:
    driver: local
